spring:
  application:
    name: CocktailApp-Backend

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080
  jetty:
    threads:
      selectors: 30
      acceptors: 10

db.url: jdbc:postgresql://rc1a-kgq9674tw9rnfx96.mdb.yandexcloud.net:6432/cocktail-db?ssl=true&sslmode=verify-full
db.username: trishlex
db.password: ""
db.driver: org.postgresql.Driver

logging:
  level:
    org.springframework.jdbc.core: TRACE
