openapi: 3.0.1
info:
  title: Cocktail API
  version: LATEST

servers:
  - url: http://localhost:8080/

paths:
  /ping:
    get:
      operationId: ping
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PingResponse'

  /cocktails:
    get:
      tags:
        - cocktail
      operationId: getCocktails
      parameters:
        - in: query
          name: start
          required: false
          schema:
            type: integer
        - in: query
          name: name
          required: true
          schema:
            type: string
        - in: query
          name: limit
          required: false
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CocktailsLightResponse'

  /cocktails/{id}:
    get:
      tags:
        - cocktail
      operationId: getCocktail
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CocktailDTO'


  /cocktails/names/{name}:
    get:
      tags:
        - cocktail
      operationId: getCocktailNames
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CocktailNamesResponse'

  /ingredients/names/{name}:
    get:
      tags:
        - ingredient
      operationId: getIngredientNames
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IngredientNamesResponse'


components:
  schemas:
    PingResponse:
      type: object
      required:
        - response
      properties:
        response:
          type: string
          nullable: false

    CocktailNamesResponse:
      type: array
      items:
        $ref: '#/components/schemas/CocktailNameDTO'

    CocktailNameDTO:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

    IngredientNamesResponse:
      type: array
      items:
        $ref: '#/components/schemas/IngredientNameDTO'

    IngredientNameDTO:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string

    CocktailsLightResponse:
      type: array
      items:
        $ref: '#/components/schemas/CocktailLightDTO'

    CocktailLightDTO:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        preview:
          type: string
          format: byte
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/CocktailIngredientDTO'

    CocktailIngredientDTO:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        preview:
          type: string
          format: byte
        amount:
          type: integer
        unit:
          type: string

    CocktailDTO:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        image:
          type: string
          format: byte
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/CocktailIngredientDTO'
        tools:
          type: array
          items:
            $ref: '#/components/schemas/CocktailToolDTO'
        instructions:
          type: array
          items:
            type: string
        description:
          type: string
        tags:
          type: array
          items:
            type: string

    CocktailToolDTO:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        preview:
          type: string
          format: byte